### ISSUE TITLE
the data category 'ihm_ordered_ensemble' is misleading

### ISSUE THREAD

**Issue by jaredsagendorf** [ihmwg/IHMCIF#88]
The data category `ihm_ordered_ensemble` is a bit misleading and inaccurate for two reasons:

1.  It is not actually an ensemble, but just a directed graph of model groups, none of which need be ensembles themselves.
2. The directed graph need not actually define a strict ordering - it can define a cycle or a tree (i.e. branched process). 

A suggested fix would be to re-name the category `ihm_partially_ordered_model_groups`. That seems descriptive enough, and should cover all cases which the current dictionary can be used to represent. The term "partially ordered" comes from the concept of partially ordered sets in mathematics: https://en.wikipedia.org/wiki/Partially_ordered_set

It may also be useful to add an optional descriptive category data item to explicitly identify if the model groups represent a strict ordering, a cycle or a branched process. This is of course implicit in the edges, but not obvious without tracing out the whole graph.

**Comment by brindakv** [comment]
This has been implemented.
